project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - discipline.qmd
    - districts.qmd
    - evolution.qmd
    - prod_analysis_px.qmd
    - bfs_delivery_prod.qmd

website:
  title: "Étudiants 2025 – CH"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: discipline.qmd
        text: Discipline
      - href: districts.qmd
        text: Districts
      - href: evolution.qmd
        text: Évolution
      - href: prod_analysis_px.qmd
        text: Production PX
      - href: bfs_delivery_prod.qmd
        text: Production BFS delivery

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
